spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
mybatis-plus:
  type-aliases-package: com.hongjf.shardingshperejdbc
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true

logging:
  level:
    root: info
  file:
    name: ./logs/sharding.log
  logback:
    rollingpolicy:
      max-history: 20
